### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kcpants** [WiiDatabase/showmiiwads-mod#2]
The program throws a `NullReferenceException` when attempting to change the channel title of several Japanese wads. Attempting to edit the channel title of the following wads on Windows will reproduce the issue:

- Mr. Heli no Daibouken
- Bomberman Panic Bomber

The stack trace is as follows:

> `System.NullReferenceException: Object reference not set to an instance of an object.
>    at ShowMiiWads.ShowMiiWads_Main.cmChannelName_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

This points to a bug in the `ShowMiiWads_Main.cmChannelName_Click` function:
https://github.com/WiiDatabase/showmiiwads-mod/blob/acf711796755c789acb48a2c41f9f348b04ed1d7/ShowMiiWads/ShowMiiWads_Main.cs#L3273

**Comment by kcpants** [comment]
The bug is on line 3284. 
https://github.com/WiiDatabase/showmiiwads-mod/blob/acf711796755c789acb48a2c41f9f348b04ed1d7/ShowMiiWads/ShowMiiWads_Main.cs#L3284 For the Japanese wads mentioned above, there is no English title set so `oldtitles[0]` is `null`.

**Comment by Brawl345** [comment]
Thanks for taking your time to fix this! I don't have a Windows PC anymore so I can't release a new version.

**Comment by kcpants** [comment]
Thanks for merging the fix! I already built a custom version for myself and renamed the Japanese WADs I was having problems with. I just wanted to make sure everyone is able to benefit from the fix whenever the next version does get released.
